### ISSUE TITLE
 Need complete  test-data format for Azure cloud  provider in cfme_data.yaml and credentials.yaml under conf folder.

### ISSUE THREAD

**Issue by ranjeetsingh-23** [ManageIQ/integration_tests#10118]
What is complete  data format for Azure cloud  provider in cfme_data.yaml and credentails.yaml under conf folder.
It is required to run all test cases related to Azure not only crud.
Below is not sufficient to run other test cases...

 ```
azure:
      name: ms azure
      type: azure
      server_zone: default
      region: East US
      region_name: East US
      tenant_id: xxxxxxxx
      subscription_id: xxxxxxx
      endpoints:
          default:
              credentials: azure
      tags:
          - default
```
