### ISSUE TITLE
Create openstack provider missing "Region" attribute in integration_test framework

### ISSUE THREAD

**Issue by jeffreyluo0428** [ManageIQ/integration_tests#9969]
cfme_data.yaml contains the following OpenStack Provider info:

```
    powervc:
        name: powervc
        type: openstack
        version: 14
        default_name: powervc
        endpoints:
            default:
                credentials: powervc
                hostname: xxxxxxx
                security_protocol: SSL without validation
                api_port: 5000
        hostname: xxxxxxxxx
        credentials: powervc
        api_version: Keystone v3
        port: 5000
        server_zone: default
        domain_id: default
        tenant_mapping: yes
        tag:
           - default     
```
From https://github.com/ManageIQ/integration_tests/blob/master/cfme/cloud/provider/openstack.py#L88", it does not have the attribute "Region" that is the optional field in Cloudform for creating Openstack Provider..

We need to add "Region" attribute in the framework,
